### ISSUE TITLE
Notification actions

### ISSUE THREAD

**Issue by davidvasquezr** [aritchie/notifications#10]
I already implemented the notifications and it works perfect, but, Can I add some action to execute when the user does touch in the notification?

**Comment by aritchie** [comment]
Not from this library.  This library allows you to store metadata to react to it when your app resumes.  You'll need to hook into the appropriate events on both platforms (iOS appdelegate & an intent filter on droid I guess)

**Comment by raymond-dillon** [comment]
Is it possible to resume the application from hitting the notification? Can you provide an example of storing metadata along with the notification?

**Comment by aritchie** [comment]
The notification object contains a dictionary where you can add the key/values.  To pick up this data, you'll need to look into each individual platform for how this metadata is retrieved.

**Comment by raymond-dillon** [comment]
Can you give me an example of using your notification object to store metadata?
