### ISSUE TITLE
Size of the Developer ID is too large for scheduled notification Exception in UWP

### ISSUE THREAD

**Issue by jotprabh1** [aritchie/notifications#11]
Hi! I have just started using Xamarin. I am trying to implement your notifications package in my project. But I get an exception on UWP on the line Notifications.Instance.Send(notification) stating that the size of the developer id is too large for scheduled notifications. I have provided my code below:

                Notification notification = new Notification();
                notification.SetMessage("New Message from App");
                notification.SetTitle("New Message");
                notification.SetSchedule(TimeSpan.FromMinutes(1));
                Notifications.Instance.Send(notification);

Can you please check what's the problem? Thanks for your help.

**Comment by jotprabh1** [comment]
I figured it out. "notificaiton.SetSchedule()" is not working on UWP. I am thinking of implementing it through a background task. I am not sure whether that's the correct approach. Any help in this regard will be highly appreciated.

**Comment by aritchie** [comment]
Please include the entire exception/stacktrace and I'll take a look

**Comment by jotprabh1** [comment]
Updated the stacktrace in the second comment

**Comment by jotprabh1** [comment]
Thanks for the update Allan! You are awesome.
