### ISSUE TITLE
Android V3.0.0 requires Xamarin.Android.Support.v4 < 24.0.0

### ISSUE THREAD

**Issue by philmoz** [aritchie/notifications#13]
Xamarin.Android.Support.v4 version 24.2.1 is nearly 6 months old, and the current release is 25.1.1.

Why does Acr.Notifications require v4 < 24.0.0?

If this is just a case of the nuget dependencies not being updated, then you could simplify things for everyone by just removing the upper limit on all the dependencies.

**Comment by aritchie** [comment]
Why am I using an old version?  Simple - I haven't had a need to update it and I'm the primary target audience of the library.  I also haven't done much work on this library in the last 6 months.

That being said, I'm not obligated to keep anything up-to-date.  I don't have to pay attention to every external library update either (hence why I closed your request for JSON.NET). 

I'm glad you get value out of this library and I am willing to help at any time, but please be a little more respectful when you file stuff in the future.
