### ISSUE TITLE
[windows] The notifications always returns the same id "1"

### ISSUE THREAD

**Issue by OurDarkLord** [aritchie/notifications#16]
Hi,
I've been implementing your notification service. It's great and works perfect on android.
But on windows there is a problem that the id is always 1.
You're still able to set multible notifications but they have all the same id 1.

**Comment by aritchie** [comment]
Thanks for letting me know.  3.1.1 on nuget that will fix this up.

**Comment by OurDarkLord** [comment]
Thanks!
