### ISSUE TITLE
Notification title assigned to AlertAction instead of AlertTitle

### ISSUE THREAD

**Issue by lidi** [aritchie/notifications#18]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [] Android
 - [] UWP
 - [] PCL

## Version of OS(s) listed above with issue
all

## Version of Library
v2.0 
https://github.com/aritchie/notifications/releases/tag/v2.0

## Expected Behaviour
notification.AlertTitle should contain provided notification title

## Actual Behavior
instead notification title is stored in AlertAction

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible
Contact GitHub

## More info:

Line: 
https://github.com/aritchie/notifications/blob/master/Acr.Notifications.iOS/NotificationsImpl.cs#L40

My pull request: 
https://github.com/aritchie/notifications/pull/17

**Comment by aritchie** [comment]
Thanks for the PR.  I can add this to v3.x.  I don't keep old versions around as I don't have the time to support them.
