### ISSUE TITLE
Feature Request: Custom IDs

### ISSUE THREAD

**Issue by hardcodet** [aritchie/notifications#19]
Would it be feasible to provide an API that allows us to specify the IDs rather than having your library generate them as sequental ints? Since the "thing" we want to schedule probably already has an identifier of sorts (I couldn't think of a use case in my code where that wouldn't be true), having to store a returned ID requires us to write caching and mapping code. An overload that would take the ID would make all that go away, e.g.

        public void SetReminder(Appointment app)
        {
            //cancel a potentially scheduled appointment
            CrossNotifications.Current.Cancel(app.Id);

            //schedule appointment
            CrossNotifications.Current.Send("Foo", "Bar", app.Timestamp, id: app.Id);
        }

Thanks for the consideration!
Philipp

**Comment by aritchie** [comment]
Thanks for the FR.  I have actually been considering this idea for a long time and I do agree with it.  I just wanted it to be set automatically or random generation.  I don't want to deal with both scenarios.

**Comment by hardcodet** [comment]
Regarding the scenarios: That would be an easy overload, not? If specified use that ID, otherwise just generate it (either using your int scheme, or by just generating a GUID? (in case you went for ints rather than strings due to a platform limitation, you probably could still use strings in the API and then hash those with a super low risk of collisions).

**Comment by aritchie** [comment]
Taking the options directly isn't hard.  It is dealing with the platforms that can be painful.

I have to watch for "collisions" of IDs as some OS's will silently take the ID and overwrite a previous notification schedule.  The other problem is that in order to cancel on android, I need to keep IDs around somewhere and I have a limited storage basin.

**Comment by hardcodet** [comment]
I don't know the specifics, so I'm sure you're better to judge. My gut feeling was that collisions shouldn't be much of a problem (or responsibility could be delegated to the caller, if solving it generically is a problem), but I might be totally wrong there.

**Comment by KoenDeleij** [comment]
Some time ago I made some quick changes to add reoccurring notifications and add id references.
Pushed the changes to my fork. Might work for you :)

**Comment by aritchie** [comment]
This is part of v4 which is due any day
