### ISSUE TITLE
Android Scheduled Notifications

### ISSUE THREAD

**Issue by Jazzeroki** [aritchie/notifications#2]
I was trying to do the following to schedule a series of messages on Android to go out.  I could get an initial message to appear which would appear right away but I could never get any further scheduled messages to appear later.  One other behavior I noted was after clicking on a notification it didn't want to reopen even the opening screen of my Xamarin Forms app.

btw thanks for fixing the json issue.

public List<string> ScheduleNotifications(string title, string message)
		{
			var notificationIDs = new List<string>();
			for (int i = 0; i < 24; i++)
			{
//var notifyTime = new TimeSpan(0,0,(i*10));
				////var notifyTime = TimeSpan.FromHours(i * 2);
				//var notification = new Notification
				//{
				//	Title = "Action Required",
				//	Message = "A timer is still running.  Please open the app and stop any running time",
				//	//Date = DateTime.Now + new TimeSpan(0, 0, (i * 10)),
				//	//When = notifyTime,
				//};
				//notification.When = notifyTime;
				var notifyTime = new TimeSpan(0, 0, (i * 10));
				var id = Acr.Notifications.Notifications.Instance.Send(title, message, "", notifyTime);
				notificationIDs.Add(id);
			}
			return notificationIDs;
		}

**Comment by aritchie** [comment]
1.5 has been released to nuget with the fix for this
