### ISSUE TITLE
Dependency issues on Android

### ISSUE THREAD

**Issue by hardcodet** [aritchie/notifications#20]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] Android

## Version of OS(s) listed above with issue

MonoAndroid, Version=v7.1, targeting .NETPortable,Version=v4.5,Profile=Profile259

## Version of Library

3.1.2

## Expected Behaviour

Expected NuGet to be installing your 3rd party libraries only.

## Actual Behavior

Any idea what's off with my setup? I attempted to install the library resolves to tons of system-level libraries at version 4.3.0, as per this screenshot:

<img src="https://cloud.githubusercontent.com/assets/873009/25614211/53721d74-2f31-11e7-8fc4-bb650c964e32.png" width="600"></img>

The only thing that stroke me odd when looking at the dependencies on NuGet was a dependency on MonoAndroid v0.0 instead of v1.0. I assume this is just my setup, but it's pretty vanilla, with an application that has been in development for several months. I tried the same with 3.1.1, but it's the same, so you wouldn't have to worry about having introduced an issue with the latest release.

**Comment by aritchie** [comment]
I usually draw the line at support requests that revolve around external dependencies like this one.  I'll help you out this one time.  This is not a defect that I have introduced.  This is simply .net standard libraries starting to come into the equation, likely from acr.settings => json.net.
