### ISSUE TITLE
Scheduled Notification on Android 

### ISSUE THREAD

**Issue by raymond-dillon** [aritchie/notifications#21]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [X] Android

## Version of OS(s) listed above with issue

Android 6.0

## Version of Library

3.1.2

## Expected Behaviour

Notification Appears after 10 seconds

## Actual Behavior

Notification doesn't not fire at all when a timespan is provided. A notification without a timespan fires OK. 

Scheduled notifications work fine on iOS.

**Comment by aritchie** [comment]
Works fine for me.  Please send a test case so I can see what is going on.

**Comment by aritchie** [comment]
No response to issue.
