### ISSUE TITLE
How do I set the notification sound to my .mp3 file in Android / Resources /raw folder

### ISSUE THREAD

**Issue by Willan-Daffo** [aritchie/notifications#22]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] Android

 - [] PCL

## Version of OS(s) listed above with issue

   Android Nougat 7.0

## Version of Library
  version: 3.1.2

## Expected Behaviour
 I want to add mymp3 file from the Resources/raw/ sound.mp3 file in the notification

## Actual Behavior
 no exception, not sure how to set notification sound to my sound.mp3 file

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible
Contact GitHub

**Comment by aritchie** [comment]
It will be in the Android documentation.  I don't remember all the ins/outs with it.  I don't do anything special under the hood:
```csharp
                var file = new File(notification.Sound);
                var uri = Android.Net.Uri.FromFile(file);
                builder.SetSound(uri);
```
