### ISSUE TITLE
UWP Exception: Method not found

### ISSUE THREAD

**Issue by Janx80** [aritchie/notifications#23]
Hi,

This line: 

`CrossNotifications.Current.Send("My Title", "My message for the notification");`

raises this exception running the UWP Project (both on Windows 10 x86/x64 machine and Windows 10 Lumia Phone).

```
Method not found: 'Windows.UI.Notofications.NotificationData
Windows.Ui.Notifications.Toastnotification.get_Data()'.
```

**Comment by aritchie** [comment]
Please use the issue template (the one you removed) next time if you want a reply.

Please include the entire stacktrace and what version of UWP you are using 10.10586 or 10.15063?

**Comment by Janx80** [comment]
Sorry, my mistake.

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [] Android
 - [x] UWP (10.10586) (Shared Project)
 - [] PCL

## Version of OS(s) listed above with issue
- (PC) Microsoft Windows 10 Pro x64
- (Lumia 650) Microsoft Windows 10 Mobile 10.0.10586.494

## Version of Library
3.2.0 Stable

## Expected Behaviour
Show a local notification in a Windows Phone App


## Actual Behavior
This line:
CrossNotifications.Current.Send("My Title", "My message for the notification");

Throws this exception:

   at Acr.Notifications.NotificationsImpl.Send(Notification notification)
   at Acr.Notifications.AbstractNotificationsImpl.Send(String title, String message, String sound, Nullable`1 when)
   at MiRitorniInMente.Views.Detail.Login.LoginPage.<OnLoginButtonClicked>d__6.MoveNext()

**Comment by aritchie** [comment]
Ok - is the issue on the phone or the PC or both... your expected behavior suggests phone, but you versions says both.  I need to know where to focus.

Secondly, are you compiling your project with the 15063 SDK as the target version with the min version of 10586?

**Comment by Janx80** [comment]
> Secondly, are you compiling your project with the 15063 SDK as the target version with the min version of 10586?

This is the solution!
I was compiling with 15063 as target and min version.

**Comment by aritchie** [comment]
excellent - glad its resolved.
