### ISSUE TITLE
Can't get sounds to work in android

### ISSUE THREAD

**Issue by ChangePlaces** [aritchie/notifications#24]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [x] Android
 - [] UWP
 - [] PCL

## Version of OS(s) listed above with issue
API 23

## Version of Library
3,2,0

## Expected Behaviour
Sound to be played: `CrossNotifications.Current.Send("Notification!", "Message!", "android.resource:///raw/horn");`

## Actual Behavior
Notification appears, but no sound appears.
Should notification drop down over current activity? If so, it doesn't.

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible
Contact GitHub

**Comment by aritchie** [comment]
I have fixed the readme so it renders the missing package name part of the path.  Sound does work on android but I'm not sure of the limitations it has.
