### ISSUE TITLE
NotificationsImpl.cs: Intent Extras for Android do not work (fix included)

### ISSUE THREAD

**Issue by leutenecker** [aritchie/notifications#25]
// Problem in Version 3.2.0 which does not fill the Intent Extras:

var launchIntent = Application.Context.PackageManager.GetLaunchIntentForPackage(Application.Context.PackageName);
            launchIntent.SetFlags(ActivityFlags.NewTask | ActivityFlags.ClearTask);

            var builder = new NotificationCompat
                .Builder(Application.Context)
                .SetAutoCancel(true)
                .SetContentTitle(notification.Title)
                .SetContentText(notification.Message)
                .SetSmallIcon(this.AppIconResourceId)
                .SetContentIntent(TaskStackBuilder
                    .Create(Application.Context)
                    .AddNextIntent(launchIntent)
                    .GetPendingIntent(id, (int)PendingIntentFlags.OneShot)
                );

            // Remove this part, compare fixed version below 
            foreach (var pair in notification.Metadata)
            {
                builder.Extras.PutString(pair.Key, pair.Value);
            }

            if (notification.Vibrate)
            {

// Fixed version of the file NotificationsImpl.cs:

            var launchIntent = Application.Context.PackageManager.GetLaunchIntentForPackage(Application.Context.PackageName);
            launchIntent.SetFlags(ActivityFlags.NewTask | ActivityFlags.ClearTask);

            foreach (var pair in notification.Metadata)
            {
                launchIntent.PutExtra(pair.Key, pair.Value);
            }

            var builder = new NotificationCompat
                .Builder(Application.Context)
                .SetAutoCancel(true)
                .SetContentTitle(notification.Title)
                .SetContentText(notification.Message)
                .SetSmallIcon(this.AppIconResourceId)
                .SetContentIntent(TaskStackBuilder
                    .Create(Application.Context)
                    .AddNextIntent(launchIntent)
                    .GetPendingIntent(id, (int)PendingIntentFlags.OneShot)
                );

            if (notification.Vibrate)
            {
                builder.SetVibrate(new long[] { 500, 500 });
            }

**Comment by Xantango** [comment]
Yeah, i'm facing the same issue, as i cannot fetch the Extras.
And the above suggestion would do the trick... :)

**Comment by aritchie** [comment]
I will look into this for the next release.  Please use the issue template in any future filings.

@Xantango +1's are really not helpful

**Comment by aritchie** [comment]
This is fixed in the upcoming v4
