### ISSUE TITLE
SQLitePCL.raw Error while using  CrossNotifications.Current.Send(new Notification() {Id=1, Title = "Order Status", Message = "Your order with ref number 0124 has been updated" });

### ISSUE THREAD

**Issue by Akinnagbe** [aritchie/notifications#26]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [X] Android 
 - [] UWP
 - [] .NET Standard

## Version of OS(s) listed above with issue
Android 6.0

## Version of Library
Acr.Notifications 4.0.0

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_
Could not set up parent class, due to: Could not set up parent class, due to: Could not load type of field 'SQLite.SQLiteConnection:<Handle>k__BackingField' (8) due to: Could not load file or assembly 'SQLitePCL.raw, Version=0.8.5.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. assembly:SQLitePCL.raw, Version=0.8.5.0, Culture=neutral, PublicKeyToken=null type:<unknown type> member:<none> assembly:/storage/emulated/0/Android/data/com.reverthmosolutions.SupplyChainMobile/files/.__override__/SQLite-net.dll type:SQLiteConnection member:<none> assembly:/storage/emulated/0/Android/data/com.reverthmosolutions.SupplyChainMobile/files/.__override__/SQLite-net.dll type:SQLiteConnectionWithLock member:<none>

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
The error is pretty specific.  It looks like a library is missing that is external to this library.  I do use sqlite under the hood and it is included as part of the nuget package.  Take a look at your reference list in your android project to see what SQLitePCL libraries are there as it looks like something wasn't installed properly.

**Comment by Akinnagbe** [comment]
Hello aritchie,
Thanks for the reply I uninstalled the package as well as all sqlite packages, cleaned the solution and rebuilt the solution. Reinstalled the package again and no more errors BUT I noticed that I didn't get any push notifications. 

Thanks

**Comment by aritchie** [comment]
Please provide a reproducible sample with the issue (and the steps to reproduce)

**Comment by aritchie** [comment]
no response - closing
