### ISSUE TITLE
Scheduled Notifications not working on Android on v4.0.0

### ISSUE THREAD

**Issue by anne-a** [aritchie/notifications#27]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [x] Android
 - [] UWP
 - [] .NET Standard

## Version of OS(s) listed above with issue
API 25

## Version of Library
4.0.0

## Expected Behaviour
When creating a Notification with a When or Date property in the future, the notification should not be triggered until the scheduled time

## Actual Behavior
The Notification is triggered straight away

I just upgraded from version 3.2.0 to version 4.0.0 and it looks like scheduled notifications are no longer working correctly in Android. Looking through the code changes, I think it might be down to the following change:

In Line 40 of the version below, we are returning the Id for scheduled notification once it has been scheduled so the code below that to trigger the notification doesn't get hit.
https://github.com/aritchie/notifications/blob/ccf38b469d4aaa269f5dda9303c35e9139898731/Plugin.Notifications.Android/NotificationsImpl.cs

However in the current version, the return statement has been removed so the code below to trigger the notification straight away is being hit.
https://github.com/aritchie/notifications/blob/master/Plugin.Notifications.Android/NotificationsImpl.cs

It looks like previously for scheduled notifications, once the scheduled time was hit, they would effectively be resent without the scheduling information to trigger the notification straight away, but this part was removed in the commit below:
https://github.com/aritchie/notifications/commit/bf3ccfa4e261f1fa9d96d812fe256f3d795b5af3#diff-97c1049a4d8db03d0341a2c99aa76433

I'm not really sure how scheduled notifications are now meant to be triggered. Happy to make a PR to help once I understand this better.

Thanks!

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
This has been resolved in 4.0.2 which has been released to nuget

**Comment by perez-danilo** [comment]
Hi,
How can i get this 4.0.2 version?
Its not at nuget.
Thanks

**Comment by aritchie** [comment]
Not sure where you are looking, but it is listed if you search for plugin.notifications
