### ISSUE TITLE
If i reboot the device the notification gone away?

### ISSUE THREAD

**Issue by perez-danilo** [aritchie/notifications#28]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [] Android
 - [] UWP
 - [] .NET Standard

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
No idea.  It depends on the OS,version, and device settings which is external to this library.

Please follow the post rules in the future
