### ISSUE TITLE
Cannot update Dbsettings - item has no PK

### ISSUE THREAD

**Issue by claudiocleberson** [aritchie/notifications#29]
Hi Aritichie,

I facing that exception that I couldn't figure the reason out,  Do you know what could cause that?

Android, using Xamarin.Forms.

Plugin version 4.00:

Exception: 

 System.NotSupportedException: Cannot update DbSettings: it has no PK
  at SQLite.SQLiteConnection.Update (System.Object obj, System.Type objType) [0x0004e] in <9b4aaa86123841b8bec74a2ddde70f09>:0 
  at SQLite.SQLiteConnection.Update (System.Object obj) [0x0000d] in <9b4aaa86123841b8bec74a2ddde70f09>:0 
  at Plugin.Notifications.NotificationsImpl.Send (Plugin.Notifications.Notification notification) [0x00034] in C:\dev\acr
otifications\Plugin.Notifications.Android\NotificationsImpl.cs:46 

 thanks in advance,

**Comment by perez-danilo** [comment]
I had this problem, the database exists, the ocors the erros.
Unistall the app, cleam tle solution, the deploy an dretry,. I think that gonna work.

**Comment by claudiocleberson** [comment]
Hi Perez,
Thanks for your tip, but it didn't work. 
I uninstalled the app, cleaned the solution(also tried by deleting the bin and obj folders). I still getting the same exception.

**Comment by aritchie** [comment]
You need to use the latest version of the plugin (4.0.2) and clean out the db.

**Comment by claudiocleberson** [comment]
I see, I installed Acr.Notification, and another package was also installed Plugin.Notification(4.0.1). I will updated and try the Plugin.Notification 4.0.2.

Thanks!

**Comment by FatMooseHenry** [comment]
Sorry to hijack, but I can only see 4.0.0 as the latest release:
https://www.nuget.org/packages/Acr.Notifications/

For me and others, where should we look for 4.0.2?
Thanks :)

**Comment by aritchie** [comment]
Acr.notifications just points to plugin.notifications now

**Comment by FatMooseHenry** [comment]
Ah thanks, found it at: 
https://www.nuget.org/packages/Plugin.Notifications/

The nuget link here:
https://github.com/aritchie/notifications
still points to https://www.nuget.org/packages/Acr.Notifications/ which confused me a bit :)
