### ISSUE TITLE
how to use Sounds?

### ISSUE THREAD

**Issue by EmilAlipiev** [aritchie/notifications#3]
I cant find any usage sample or what this sounds is for? Can you please explain? is it for playing any sound?

**Comment by aritchie** [comment]
I'll update the samples when I have time.  It basically is a string name for a resource file on each platform.  Review the documents of each platform on how to store those resource files

**Comment by EmilAlipiev** [comment]
You mean it is name for a Sound Resource? And we can play any sound from xamarin forms project?

**Comment by aritchie** [comment]
Xamarin forms is irrelevant in this question.  It is what the api for each OS will do.  Take a look at the apple and android docs to see the restrictions and setup
