### ISSUE TITLE
Scheduled notification not working on Android

### ISSUE THREAD

**Issue by IeuanWalker** [aritchie/notifications#32]
Scheduled notification not working on Android but works on UWP.
Code used
```
 Notification notification = new Notification
 {
     Title   = "test title",
     Message = "test message",
     Date = DateTime.Now.AddSeconds(5)
 };

await CrossNotifications.Current.Send(notification);
```

 - Android

## Version of OS(s) listed above with issue
Min Android Versions - Android 4.0.3 (API Level  15 - Ice cream Sandwich)
Target Android Version - Android 6 - API Level 23

## Version of Library
4.0.2

## Expected Behaviour
Receive notification 5 seconds after button click

## Actual Behavior
Nothing

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
can you please provide a reproducible sample.  I'm not experiencing the issue.  It may also be related to #31

**Comment by IeuanWalker** [comment]
@aritchie sorry for the long reply, If I have time sometime this week ill create a project to show the problem. As for your other suggestion, I do have an icon.png in the resources > drawable folders and I have set the application icon in the android manifest.

**Comment by IeuanWalker** [comment]
@aritchie hi, I've technically found the problem. For some reason, the notifications don't work on the emulator but work on my actual phone. Do u know what could cause this?

**Comment by IeuanWalker** [comment]
@aritchie I also just wondering one the nuget package installs 2 packages?

**Comment by aritchie** [comment]
No idea why it won't work on the emulator for you.  As I said, I would need something reproducible.

The package name changed to Plugin.Notifications.  Acr.Notifications just redirects.

**Comment by IeuanWalker** [comment]
@aritchie Ok ill see what I can do, does that mean I can uninstall Acr.notification and just have Plugin.Notification?

**Comment by aritchie** [comment]
No follow up received.  Closing
