### ISSUE TITLE
await CrossNotifications.Current.Send THROWS NotSupportedException

### ISSUE THREAD

**Issue by drznathou** [aritchie/notifications#33]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [X] Android
 - [] UWP
 - [X] .NET Standard

## Version of OS(s) listed above with issue
Android 7.0 API 24

## Version of Library
V4.0.0

## Expected Behaviour
Expected to actually send a Notification ^^

## Actual Behavior
in Project Core
`await CrossNotifications.Current.Send(new Notification
                {  Message = "Yo", Vibrate = true, Title = "yo", When = TimeSpan.FromSeconds(10)});`

Throws

{System.NotSupportedException: Cannot update DbSettings: it has no PK
  at SQLite.SQLiteConnection.Update (System.Object obj, System.Type objType) [0x00039] in /Users/vagrant/git/src/SQLite.cs:1474 
  at SQLite.SQLiteConnection.Update (System.Object obj) [0x00005] in /Users/vagrant/git/src/SQLite.cs:1445 
  at Plugin.Notifications.NotificationsImpl.Send (Plugin.Notifications.Notification notification) [0x00034] in C:\dev\acr\notifications\Plugin.Notifications.Android\NotificationsImpl.cs:46 
  at NegoTransMobile.Core.Views.Pages.LoginPage+<LoginButton_Click>d__5.MoveNext () [0x0011d] in blablabla.cs:179 }

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
Upgrade the nuget package Plugin.Notifications to 4.0.2.  This has already been resolved.

**Comment by drznathou** [comment]
Thanks for your answer @aritchie , 
I was actually using Plugin.Notifications 4.0.2.
What I did is installing Acr.Notifications yesterday which installed the lastest version of Plugin.Notifications 4.0.2 before I knew Acr.Notifications project moved. So, this morning,  I uninstalled Acr.Notifications and uninstalled/installed Plugin.Notifications.
The result  :fast_forward: it throws the same exception  :confused:
Do you need more info?  :disappointed_relieved:

**Comment by drznathou** [comment]
OK did some packages update even thought, My pcl targeting framework is .Net Standard 1.3 It works

**Comment by mtbgithub** [comment]
I've updated every package in my project and am using 4.0.2 - I still get this error.  Not using PCL, using shared.
