### ISSUE TITLE
Update to android Nuget Packages clashes with plugin

### ISSUE THREAD

**Issue by IeuanWalker** [aritchie/notifications#36]
Trying to update all android NuGet packages but I get a conflict with this plugin.
![image](https://user-images.githubusercontent.com/6544051/31884085-ef830774-b7e3-11e7-8208-343d61b48f01.png)

 - [] Android

## Version of Library
v4.0.2

**Comment by aritchie** [comment]
This is not a problem with the plugin.  As stated in the issue template, please do not request library updates like this.
