### ISSUE TITLE
How to send Local Notifications when App is closed (Not backgrounded but closed at all or swiped out) 

### ISSUE THREAD

**Issue by Srinivasdelta** [aritchie/notifications#37]
How to send Local Notifications when App is closed (Not backgrounded but closed at all or swiped out) in Xamarin Forms.  It's working fine when app is running on background but when I close the app it's not working. I am not able to send local push notifications when app was closed.

**Comment by aritchie** [comment]
Follow the issue template (the one you deleted) in the future if you want help.  

I'm assuming this is android and that the data is future dated.  I use the alarm manager, but I don't engage anything responsible for keeping your app alive.  That's for your app code to decide.  You can use an android stick service to keep your app alive if needed.

**Comment by Srinivasdelta** [comment]
Ok sure thanks for ur help. I will Follow . sorry about that.
