### ISSUE TITLE
Repeat notification intervals

### ISSUE THREAD

**Issue by thorradin** [aritchie/notifications#38]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)
We are coding this app using Xamarin.Forms (Portable)
 - [] iOS
 - [] Android

## Version of OS(s) listed above with issue

- iOS version 11.2
- Android version 7.1

## Version of Library

4.0.0

## Expected Behaviour
------------------------------------------------------------------
//Code Snippet
   var notif1 = CrossNotifications.Current.Send(new Notification
                                {
                                    Id = id++,
                                    Title = "Hi",
                                    Message = "This is a notifications",
                                    Date = classTime.AddMinutes(-(40)),
                                    Vibrate = true,
                                    When= TimeSpan.FromDays(300)
                                });
---------------------------------------------------------------------
Expected Behaviour: To get the **notification repeated every day for 300 days**

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_
 Actual Behavior: **When** statement doesn't work at all.
And we get the notification for one day only.

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
There is no repeat functionality in this plugin at this time

**Comment by ManojMali0807** [comment]
Hi @aritchie ,

The plugin is awesome. I am using this for one of my application.
I just want to request you to add the repeat notification functionality also.

Thank you

**Comment by aritchie** [comment]
@ManojMali0807 I have no plans to add this right now as I don't have a need for it.  It is also extremely rude to request a feature with a timeline from a free OSS library.  Why not contribute back to something that provides you value?  I'd be happy to take a PR

**Comment by thorradin** [comment]
Maybe Manoj is new to this Github society. But you have to know that it is unprofessional to ask someone that, in here. It's an open source society, and aritchie did more than enough just by sharing this plug in, we love it and we thank you very much aritchie. Keep up the good work and don't feel pressured to do anything outside of your plans.  :)

**Comment by ManojMali0807** [comment]
Hi @aritchie ,
Sorry if my post hurt you, that was not my intention.

@thorradin Thank you for your guidance.
I will take care now on words while posting comments.
