### ISSUE TITLE
How do I handle when the notification was tapped.

### ISSUE THREAD

**Issue by gimkim** [aritchie/notifications#39]
How do I handle when the notification was tapped.

On android i've tried setting the Mainactivity with all LaunchMode SingleInstance,SingleTop,SingleTask.
But all give the same result. 
When i tapped the notification, It just launch another instance of an app replacing the current one.

How do i create something to handle the parameter received from the notification and use the messagingcenter to trigger some event instead of re-launching the entire app???

Thanks.

**Comment by aritchie** [comment]
Please look this up online.  This doesn't have anything to do with this library.  I am looking into adding an event in a later release.
