### ISSUE TITLE
can i repeat the sound until user response just like Alarm

### ISSUE THREAD

**Issue by sunnysannii102** [aritchie/notifications#40]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [] Android
 - [] UWP
 - [] .NET Standard

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
No

**Comment by sunnysannii102** [comment]
hy sir!
  Notification noti = new Notification();
            noti.Title = "title";
            noti.Message = "messsage";
          noti.Sound = "alarms";
            noti.Vibrate = true;
          
            noti.When = TimeSpan.FromSeconds(5);
         

            await CrossNotifications.Current.Send(noti);
           i used this code and place sound file for android in Resources/raw/sounds/alarms.mp3 and set buildAction to android resource but sound is not working can you guide where i am goin wrong best regards
