### ISSUE TITLE
await CrossNotifications.Current.Send return void

### ISSUE THREAD

**Issue by SyaoranChang** [aritchie/notifications#42]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [X] Android
 - [] UWP
 - [X] .NET Standard

## Version of OS(s) listed above with issue
Android 7.1.0

## Version of Library
Acr.Notifications 4.0.0

## Actual Behavior
var id = await CrossNotifications.Current.Send(new Notification
            {
                Title = "HELLO!",
                Message = "Hello from the ACR Sample Notification App",
            });

Build error:
c# - Cannot assign void to an implicitly-typed

**Comment by aritchie** [comment]
Look at the interface https://github.com/aritchie/notifications/blob/master/Plugin.Notifications.Abstractions/INotifications.cs

There is no return value on it
