### ISSUE TITLE
Redirect when click on the notification

### ISSUE THREAD

**Issue by dramos1138** [aritchie/notifications#44]
Is there any way to redirect to any specific URL or page when the user clicks on the notification?

Thanks!

**Comment by aritchie** [comment]
You can use the CrossNotifications.Current.Activated event in v5 which is out as a nuget pre-release.

You can also use the notification metadata and install the appropriate hooks on iOS appdelegate or via an android service

**Comment by dramos1138** [comment]
Thank you very much Allan, I´m tryin to implement the Activated event, but nothing happens, here's my code:

private async void Notif()
        {            
            try
            {
                var notificacion = new Notification
                {
                    Id = 1,
                    Date = DateTime.Today,
                    Message = "Service Suspended",
                    Title = "Alert",
                    When = TimeSpan.FromSeconds(5)
                };
                
                await CrossNotifications.Current.Send(notificacion);

                CrossNotifications.Current.Activated += OnActivated;

            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        void OnActivated(object sender, Notification e)
        {
            
        }
