### ISSUE TITLE
Default Sound Not Playing on iOS notification

### ISSUE THREAD

**Issue by dberroa** [aritchie/notifications#46]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [] Android
 - [x] .NET Standard

## Version of OS(s) listed above with issue

11
.Net standard 2

## Version of Library

4.0.0

## Expected Behaviour

I expect the default sound to play for the system on iOS.

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_

I don't hear any sound. I don't supply a sound to the notification as I thought I saw the default value of a notification sound is DefaultSound in your code. I don't believe I see that being used anywhere though. Set vibrate to true.

The notification does come up but does not vibrate or make a sound.

The only code I have is as follows in the net standard library:

```
//Show a local notification once the photo has been processed.
await CrossNotifications.Current.Send(new Notification()
{
    Message = $"Your photos for property {Property.PropertyID} have been processed.",
    Title = "Photo Processing Complete",
    Id = Property.PropertyID.Value,
    Vibrate = true,
    Date = next5
});
```

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
Nope - I don't set any sound.  You have to pass one yourself.
