### ISSUE TITLE
Pre-release Activated doesn't work

### ISSUE THREAD

**Issue by dramos1138** [aritchie/notifications#47]
Thank you very much Allan, I´m tryin to implement the Activated event, but nothing happens, here's my code:

private async void Notif()
{
try
{
var notificacion = new Notification
{
Id = 1,
Date = DateTime.Today,
Message = "Service Suspended",
Title = "Alert",
When = TimeSpan.FromSeconds(5)
};
await CrossNotifications.Current.Send(notificacion);
CrossNotifications.Current.Activated += OnActivated;
}
catch (Exception ex)
{
throw ex;
}
}

void OnActivated(object sender, Notification e)
{

}

**Comment by aritchie** [comment]
This is in beta.  I'm still working on some things.  Please be patient or use the native built in methods in iOS AppDelegate or Android broadcast receivers.

That event in any case, will need to go in the main starting points of your application.  Those docs are in dev at the moment

**Comment by dramos1138** [comment]
Thanks Dude!
