### ISSUE TITLE
Notification shows up right away instead of waiting for scheduled time

### ISSUE THREAD

**Issue by hushyon** [aritchie/notifications#50]
Code:

                    await CrossNotifications.Current.Send(new Notification
                    {
                        Id = 1,
                        Title = "Test title here",
                        Message = "Test message here",
                        When = TimeSpan.FromSeconds(10),
                    });

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [v] Android
 - [] UWP
 - [] .NET Standard

## Version of OS(s) listed above with issue
Min. 4.0.3
Target 8.0

## Version of Library
4.0

## Expected Behaviour
Notification waits for 10 seconds and show.

## Actual Behavior
Notification shows up right away.

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
When will be gone in the next release.  Just use 'Date'.  Couldn't reproduce anyhow
