### ISSUE TITLE
Android Vibration Notifications

### ISSUE THREAD

**Issue by De4th69** [aritchie/notifications#7]
Hi,
sorry if this is a stupid question, but is there a way to use the Vibration with a scheduled notification?
Right now it doesn't vibrate when I add a scheduled one and in your source there's a vibrate method. But no event to hook the method onto.

**Comment by aritchie** [comment]
Not a stupid question at all.  It looks like a defect which should be easy to fix sometime today.

The only thing I would ask in the future is what platform(s) you experienced this issue on.  

Visual inspection of the code suggests both iOS and android (not available on Windows from what I've seen)

**Comment by De4th69** [comment]
I've experienced it on Android. Can't say it for iOS though.

Yeah I looked to get this to work before I found your Plugin and it's not available on Windows.

**Comment by De4th69** [comment]
Oh I didn't recognized that you changed the title. So it should've worked?

A little side question if your not bothered. But how would you add notifications based on Dates given for Appointments? Right now I'm calculating the difference like this:

`var notificationTime = (int)(DateTime.Now - Appointment.CombinedStartDate).TotalMinutes + Appointment.Reminder;`

And then adding it to the notification like this : `TimeSpan.FromMinutes(Math.Abs(notificationTime))`
Is this the correct way to use your Plugin?

**Comment by aritchie** [comment]
Actually, this is being downgraded to an enhancement because vibration requests only exist on android.

As for your question, you can use the method that takes a full Notification object.  You can set the Date which takes a full DateTime object or you can use When which takes a timespan.  In this case, it sounds like you want to be able to just set the date.

**Comment by De4th69** [comment]
Wait what? How could I have missed that! Awesome thank you :+1: 

Yeah that's true, it's only working for android. I have some code flinging around from my attempt that could help you if you're interested

**Comment by aritchie** [comment]
Added as part of 2.0
