### ISSUE TITLE
Where to place sound assets

### ISSUE THREAD

**Issue by sivamuralidhar3** [aritchie/notifications#8]
Hi @aritchie can you tell me where to place the sound assets and how to give the path of them.

**Comment by aritchie** [comment]
Please read the iOS and android documentation on this.  I only pass string paths through to their implementations

**Comment by EmilAlipiev** [comment]
@sivamuralidhar3 have you ever figured out? I tried assets, resources and as embedded resource but none of them didnt work for me.
