### ISSUE TITLE
Notifications in Background

### ISSUE THREAD

**Issue by sirfilipef** [aritchie/notifications#9]
Hello aritchie, I'm really interested to use your notifications nuget, but I want to ask you if is possible to send notifications while the app is in background. TY

**Comment by aritchie** [comment]
Yes.  They can be triggered via time or from a background process

**Comment by EmilAlipiev** [comment]
@aritchie can you please explain what do you mean by "via time"? Is that supposed to be something like below? because I tested but it doesnt fire when it app is in the background.

```
  Notification notification = new Notification
                        {
                            Date = e.Appointment.StartTime.AddHours(-3),
                            Message =   message,
                            Title = title,
                            Vibrate = true                    
                        };
                 
```       CrossNotifications.Current.Send(notification);

**Comment by aritchie** [comment]
@EmilAlipiev It means the time you want the message to fire.  In the case you have there, I don't know what the value of the StartTime is, but it needs to be set in the future.
